Task11
AlexeyKravtsov95/surf_courses_dart pull request #12
Opened 2024-04-08 08:30 UTC by AlexeyKravtsov95

2024-04-08 11:09 UTC, Evgenia-bit requested changes
Задание выполнено ✅ 
Но нужно несколько моментов, связанных с чистотой кода, поправить.
Пройдитесь по коду, найдите все тексты, шрифты, цвета, ссылки на ресурсы (пути до изображений), создайте пупку assets в lib и в ней файлы с классами:
```dart
// strings.dart

/// Строковые константы приложения
class AppStrings {
  static const appTitle = 'Это тайтл';
}

// assets.dart
class AppAssets {
  static const favorite = 'res/icons/heart_icon.svg';
}


// typography.dart
class AppTypography {
  static const textText16Regular = TextStyle(
    fontSize: 16.0,
    height: 1.25,
    fontWeight: FontWeight.w400,
  );
}

// colors.dart
class AppColors {
  static const myColor = Colors.red;
}
```
Это сделает код более поддерживаемым.


Также пройдитесь по подсказкам анализатора кода и сделайте то, что он просит. Например, здесь нужно добавить const перед ProductTotalWidget().
<img width="522" alt="Screenshot 2024-04-08 at 14 01 37" src="https://github.com/AlexeyKravtsov95/surf_courses_dart/assets/63193897/46555287-9be9-4feb-bd9a-a68ba582a2ed">

На будущее:
- возьмите за привычку писать документацию ко всем публичным классам и методам, о правилах документирования:  https://dart.dev/effective-dart/documentation
- давайте будем делать для каждого задания отдельноe приложение, а не копить их все в папке lib. Если вы путаетесь как лучше сделать, то в следующий раз:
1. Сделайте пустой репозиторий под конкретное задание. 
2. Создайте шаблонный проект флаттер и запуште его с коммитом init.
3. Сделайте новую ветку и в ней выполните задание.
4. Создайте пулреквест чтобы можно было проверить ваш код.
5. Приложите видео как работает ваш шедевр 🤗

2024-04-08 11:09 UTC, Evgenia-bit commented on flutters_project/lib/task11/service/sort_product.dart
> +  final sortedList = products..sort((a, b) => a.price.compareTo(b.price));
Не обязательно создавать здесь переменную, можно вернуть результат сразу:
```dart
List<ProductEntity> sortToHightPrice(List<ProductEntity> products) {
  return products..sort((a, b) => a.price.compareTo(b.price));
}
```

2024-04-08 11:09 UTC, Evgenia-bit commented on flutters_project/lib/task11/service/sort_manager.dart
> +class SortManager {
Было бы удобно все методы сортировки переместить в этот класс и сделать приватными, поскольку они используются только в нем внутри метода sortType.

2024-04-08 16:54 UTC, AlexeyKravtsov95 commented on flutters_project/lib/task11/service/sort_manager.dart
> +class SortManager {
Перенес

2024-04-08 16:56 UTC, AlexeyKravtsov95 commented
@Evgenia-bit Замечания поправил, за исключением, что цвета и стиль текстов по-другому вынес, прочитал про 
https://docs.flutter.dev/cookbook/design/themes

2024-04-09 08:08 UTC, Evgenia-bit commented
> https://docs.flutter.dev/cookbook/design/themes

В небольшом приложении можно и так оставить, но в больших проектах мы обычно выносим тему в отдельный файл и ссылаемся на нее из MaterialApp. То есть разбиваем код на файлы :)

2024-04-09 08:33 UTC, merged